-- ! Auto-generated by matugen — do not edit. Edit ~/simpbar/matugen/hyprland-colors.lua instead.
--
-- Load at the END of ~/.config/hypr/hyprland.lua (after hyprland-simpbar so
-- the Material You values win):
--   pcall(require, "matugen-colors")
--
-- Exports the full MD3 dark palette as a table, and applies the border colors
-- via hl.config(). pcall in the caller keeps a missing/partially-written file
-- from breaking the compositor.

local M = {}

M.primary                = "{{ colors.primary.dark.hex_stripped }}"
M.on_primary             = "{{ colors.on_primary.dark.hex_stripped }}"
M.primary_container      = "{{ colors.primary_container.dark.hex_stripped }}"
M.on_primary_container   = "{{ colors.on_primary_container.dark.hex_stripped }}"
M.secondary              = "{{ colors.secondary.dark.hex_stripped }}"
M.on_secondary           = "{{ colors.on_secondary.dark.hex_stripped }}"
M.secondary_container    = "{{ colors.secondary_container.dark.hex_stripped }}"
M.on_secondary_container = "{{ colors.on_secondary_container.dark.hex_stripped }}"
M.tertiary               = "{{ colors.tertiary.dark.hex_stripped }}"
M.on_tertiary            = "{{ colors.on_tertiary.dark.hex_stripped }}"
M.tertiary_container     = "{{ colors.tertiary_container.dark.hex_stripped }}"
M.on_tertiary_container  = "{{ colors.on_tertiary_container.dark.hex_stripped }}"
M.error                  = "{{ colors.error.dark.hex_stripped }}"
M.on_error               = "{{ colors.on_error.dark.hex_stripped }}"
M.error_container        = "{{ colors.error_container.dark.hex_stripped }}"
M.on_error_container     = "{{ colors.on_error_container.dark.hex_stripped }}"
M.surface                = "{{ colors.surface.dark.hex_stripped }}"
M.surface_dim            = "{{ colors.surface_dim.dark.hex_stripped }}"
M.surface_bright         = "{{ colors.surface_bright.dark.hex_stripped }}"
M.surface_variant        = "{{ colors.surface_variant.dark.hex_stripped }}"
M.on_surface             = "{{ colors.on_surface.dark.hex_stripped }}"
M.on_surface_variant     = "{{ colors.on_surface_variant.dark.hex_stripped }}"
M.outline                = "{{ colors.outline.dark.hex_stripped }}"
M.outline_variant        = "{{ colors.outline_variant.dark.hex_stripped }}"
M.surface_container_lowest = "{{ colors.surface_container_lowest.dark.hex_stripped }}"
M.surface_container_low    = "{{ colors.surface_container_low.dark.hex_stripped }}"
M.surface_container        = "{{ colors.surface_container.dark.hex_stripped }}"
M.surface_container_high   = "{{ colors.surface_container_high.dark.hex_stripped }}"
M.surface_container_highest = "{{ colors.surface_container_highest.dark.hex_stripped }}"
M.inverse_surface         = "{{ colors.inverse_surface.dark.hex_stripped }}"
M.inverse_on_surface      = "{{ colors.inverse_on_surface.dark.hex_stripped }}"
M.inverse_primary         = "{{ colors.inverse_primary.dark.hex_stripped }}"
M.shadow                  = "{{ colors.shadow.dark.hex_stripped }}"

-- Apply Material You window borders.
hl.config({
    general = {
        col = {
            active_border   = { colors = { "rgb(" .. M.primary .. ")" } },
            inactive_border = "rgb(" .. M.outline_variant .. ")",
        },
    },
})

return M